### ISSUE TITLE
Roberto Pastor's long resume link is broken

### ISSUE THREAD

**Issue by tkoyama010** [RobPasMue/RobPasMue#1]
Roberto Pastor's long resume link is broken.
https://github.com/RobPasMue/RobPasMue/blob/2a435626f6c617b2a3c3cf31d313e80a279f0702/README.md?plain=1#L17

**Comment by RobPasMue** [comment]
Yep, precisely. I am currently working on it in fact but it is not ready to publish. That's why I used the ``:soon:`` arrow. Thanks for setting this as a reminder @tkoyama010!

It will be coming from here probably... https://github.com/RobPasMue/robpasmue.github.io/pull/1

**Comment by tkoyama010** [comment]
> That's why I used the :soon: arrow. 

Ah! That makes sense :)
